
import { GoogleGenAI } from "@google/genai";
import { Issue, EmailNotification, User } from "../types";

export type NotificationAction = 
  | 'NEW_REPORT' 
  | 'STATUS_CHANGE' 
  | 'LOGIN_ALERT' 
  | 'PASSWORD_RESET'
  | 'REPORT_RESULT_TO_CITIZEN';

export const composeAndSendEmail = async (
  recipientEmail: string, 
  action: NotificationAction,
  data: { issue?: Issue; user?: User; resetLink?: string }
): Promise<EmailNotification | null> => {
  // Use named parameter for apiKey and direct process.env usage
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  let prompt = "";
  let subject = "";
  let type: EmailNotification['type'] = 'UPDATE';

  switch (action) {
    case 'LOGIN_ALERT':
      subject = `[Security] New Login for ${data.user?.username}`;
      type = 'SECURITY';
      prompt = `Draft a short, firm security email to ${data.user?.name}. State that a new login occurred. Include "This is an automated security protocol".`;
      break;
    case 'NEW_REPORT':
      subject = `[Action Required] New Ward Report: ${data.issue?.title}`;
      type = 'DISPATCHED';
      prompt = `Draft a professional email to a Bengaluru Ward Councillor about a new report: ${data.issue?.title}. Mention it was filed by ${data.issue?.reportedBy}.`;
      break;
    case 'STATUS_CHANGE':
      subject = `Progress Update: ${data.issue?.title}`;
      type = 'UPDATE';
      prompt = `Draft a polite update for a citizen. Their report "${data.issue?.title}" is now "${data.issue?.status}". Thank them for being an active citizen.`;
      break;
    case 'PASSWORD_RESET':
      subject = `Reset your Password - Fix My Ward`;
      type = 'RESET';
      prompt = `Draft a password reset email for ${data.user?.name}. Link: ${data.resetLink}. Express urgency (15 mins).`;
      break;
    case 'REPORT_RESULT_TO_CITIZEN':
      subject = `Report Processed: ${data.issue?.title}`;
      type = 'UPDATE';
      prompt = `Draft a detailed summary for a citizen about their recent infrastructure report "${data.issue?.title}". AI analysis highlights: ${data.issue?.aiAnalysis}. Thank them for contributing to a better ward.`;
      break;
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      // Use correct contents structure as per guidelines
      contents: { parts: [{ text: prompt }] }
    });

    const notification: EmailNotification = {
      to: recipientEmail,
      subject,
      // Access text property directly
      body: response.text || "Message auto-generated by Fix My Ward System.",
      type
    };

    // Simulate SMTP delay
    await new Promise(r => setTimeout(r, 1500));
    console.log(`%c📧 VIRTUAL_SMTP: ${subject} -> ${recipientEmail}`, "color: #6366f1; font-weight: bold;");
    
    return notification;
  } catch (error) {
    console.error("Failed to generate notification email:", error);
    return null;
  }
};
